//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAutoRotate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("undefined")]
        public string port {
            get {
                return ((string)(this["port"]));
            }
            set {
                this["port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint display {
            get {
                return ((uint)(this["display"]));
            }
            set {
                this["display"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display1_landscape_pos_x {
            get {
                return ((long)(this["display1_landscape_pos_x"]));
            }
            set {
                this["display1_landscape_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display1_landscape_pos_y {
            get {
                return ((long)(this["display1_landscape_pos_y"]));
            }
            set {
                this["display1_landscape_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display1_portrait_pos_x {
            get {
                return ((long)(this["display1_portrait_pos_x"]));
            }
            set {
                this["display1_portrait_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display1_portrait_pos_y {
            get {
                return ((long)(this["display1_portrait_pos_y"]));
            }
            set {
                this["display1_portrait_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display2_landscape_pos_x {
            get {
                return ((long)(this["display2_landscape_pos_x"]));
            }
            set {
                this["display2_landscape_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display2_landscape_pos_y {
            get {
                return ((long)(this["display2_landscape_pos_y"]));
            }
            set {
                this["display2_landscape_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display2_portrait_pos_x {
            get {
                return ((long)(this["display2_portrait_pos_x"]));
            }
            set {
                this["display2_portrait_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display2_portrait_pos_y {
            get {
                return ((long)(this["display2_portrait_pos_y"]));
            }
            set {
                this["display2_portrait_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display3_landscape_pos_x {
            get {
                return ((long)(this["display3_landscape_pos_x"]));
            }
            set {
                this["display3_landscape_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display3_landscape_pos_y {
            get {
                return ((long)(this["display3_landscape_pos_y"]));
            }
            set {
                this["display3_landscape_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display3_portrait_pos_x {
            get {
                return ((long)(this["display3_portrait_pos_x"]));
            }
            set {
                this["display3_portrait_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display3_portrait_pos_y {
            get {
                return ((long)(this["display3_portrait_pos_y"]));
            }
            set {
                this["display3_portrait_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display4_landscape_pos_x {
            get {
                return ((long)(this["display4_landscape_pos_x"]));
            }
            set {
                this["display4_landscape_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display4_landscape_pos_y {
            get {
                return ((long)(this["display4_landscape_pos_y"]));
            }
            set {
                this["display4_landscape_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display4_portrait_pos_x {
            get {
                return ((long)(this["display4_portrait_pos_x"]));
            }
            set {
                this["display4_portrait_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display4_portrait_pos_y {
            get {
                return ((long)(this["display4_portrait_pos_y"]));
            }
            set {
                this["display4_portrait_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display5_landscape_pos_x {
            get {
                return ((long)(this["display5_landscape_pos_x"]));
            }
            set {
                this["display5_landscape_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display5_landscape_pos_y {
            get {
                return ((long)(this["display5_landscape_pos_y"]));
            }
            set {
                this["display5_landscape_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display5_portrait_pos_x {
            get {
                return ((long)(this["display5_portrait_pos_x"]));
            }
            set {
                this["display5_portrait_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long display5_portrait_pos_y {
            get {
                return ((long)(this["display5_portrait_pos_y"]));
            }
            set {
                this["display5_portrait_pos_y"] = value;
            }
        }
    }
}
